---
name: Open Pull Request

on: [pull_request]

jobs:
  run_checks:
    name: Run Linter
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: "*.sh"
          exclude: "./.git/*"

  build_amd64:
    name: Build code on AMD64 Architecture
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: troyfontaine/half-life2-dm-local:latest
